vars: &variables
  stretchFactor: ${customization.yml:biomeSpread.sinkHoles.stretchFactor}
  angle: ${customization.yml:biomeSpread.sinkHoles.angle}
  size: ${customization.yml:biomeSpread.sinkHoles.size}
  borderSize: ${customization.yml:biomeSpread.sinkHoles.borderSize}

sinkholeSampler: &sinkholeSampler
  type: EXPRESSION
  variables: *variables
  expression: |
    warpedCells(rotate(x, z, angle), rotate(z, x, angle))
  functions:
    rotate:
      arguments: [x, y, rad]
      expression: x * cos(rad) - y * sin(rad)
  samplers:
    warpedCells:
      dimensions: 2
      type: DOMAIN_WARP
      amplitude: 20
      warp:
        type: OPEN_SIMPLEX_2
        frequency: 0.01
      sampler:
        dimensions: 2
        type: EXPRESSION
        variables: *variables
        expression: |
          if (-flatCells(x / stretchFactor, z) - size > 0, flatCellsVariation(x / stretchFactor, z), -1)
        samplers: &samplers
          flatCells:
            dimensions: 2
            type: CELLULAR
            frequency: ${customization.yml:biomeSpread.sinkHoles.frequency}
            jitter: 0.3
            distance: Euclidean
          flatCellsVariation:
            dimensions: 2
            type: CELLULAR
            frequency: ${customization.yml:biomeSpread.sinkHoles.frequency}
            jitter: 0.3
            return: CellValue

sinkholeSamplerOuter: &sinkholeSamplerOuter
  type: EXPRESSION
  variables: *variables
  expression: |
    warpedCells(rotate(x, z, angle), rotate(z, x, angle))
  functions:
    rotate:
      arguments: [x, y, rad]
      expression: x * cos(rad) - y * sin(rad)
  samplers:
    warpedCells:
      dimensions: 2
      type: DOMAIN_WARP
      amplitude: 20
      warp:
        type: OPEN_SIMPLEX_2
        frequency: 0.01
      sampler:
        dimensions: 2
        type: EXPRESSION
        variables: *variables
        expression: |
          // positive / higher = solid
          if (-flatCells(x / stretchFactor, z) - size + borderSize > 0, flatCellsVariation(x / stretchFactor, z), -1)
        samplers: *samplers

stages:
  - type: REPLACE
    from: ALL
    to:
      SELF: 18
      SINKHOLE_OUTER : 3
    sampler: *sinkholeSamplerOuter
    range: &range
      min: -55
      max: 319
  - type: REPLACE
    from: ALL
    to:
      SELF: 18
      SINKHOLE_FROZEN : 1
      SINKHOLE_FOREST : 1
      SINKHOLE_JUNGLE : 1
    sampler: *sinkholeSampler
    range: *range