id: SNOWY_MEADOW
type: BIOME
extends:
  - COLOR_FROZEN
  - ENVIRONMENT_LAND_CONTINENTAL_SUBARCTIC
  - EQ_LAND
  - CARVING_LAND
  - BASE
color: $biomes/colors.yml:SNOWY_MEADOW

tags:
  - LAND_CAVES
  - USE_RIVER

vanilla: minecraft:snowy_plains

ocean:
  palette: FROZEN_OCEAN

palette:
  - GRASS_SNOW_MIX: $meta.yml:top-y
  - SAND: $meta.yml:ocean-level
  - << meta.yml:palette-bottom

slant:
  - threshold: 0.4
    palette:
      - BLOCK:minecraft:stone: $meta.yml:top-y
      - << meta.yml:palette-bottom

features:
  landforms:
    - BOULDERS
    - SMALL_BOULDER_PATCHES
  slabs:
    - SNOW_LAYERS
  trees:
    - SPARSE_SPRUCE_TREES
  preprocessors:
    - POWDER_SNOW_DEPOSITS
  postprocessors:
    - TREE_SNOW