id: MARSH
type: BIOME
extends:
  - ENVIRONMENT_LAND_MARITIME_WET
  - EQ_WARPED_WETLANDS
  - CARVING_OCEAN
  - BASE
color: $biomes/colors.yml:MARSH

vanilla: minecraft:swamp

tags:
  - LAND_CAVES
  - USE_RIVER_TEMPERATE_MARSH

palette:
  - GRASS: $meta.yml:top-y
  - GRASS_MARSH: ${meta.yml:ocean-level} + 11
  - SAND: $meta.yml:ocean-level
  - << meta.yml:palette-bottom

slant:
  - threshold: 0.4
    palette:
      - BLOCK:minecraft:stone: $meta.yml:top-y
      - << meta.yml:palette-bottom

features:
  flora:
    - TALL_GRASS
    - SUGAR_CANE
    - SMALL_DRIPLEAF
    - BIG_DRIPLEAF
