id: TEMPERATE_SEA_ARCHES
type: BIOME
extends:
  - ENVIRONMENT_LAND_MARITIME_WET
  - CARVING_OCEAN
  - BASE
color: $biomes/colors.yml:TEMPERATE_SEA_ARCHES

vanilla: minecraft:beach

vars: &variables
  base: 80
  erosionTop: 100
  erosionMiddle: 65
  erosionBottom: 55
  erosionStrength: 4

terrain:
  sampler:
    type: EXPRESSION
    dimensions: 3
    variables: *variables
    expression: |
      -y + base
      + (simplex(x,z)+1)/2 * 50
      - lerp(y,
        erosionTop, 0,
        erosionMiddle,
        lerp(y,
          erosionMiddle, erosionStrength * lerp(|erosion(x,z)|,0,1,1,0) * (-y+erosionTop),
          erosionBottom, 0
        )
      )
    samplers:
      erosion:
        dimensions: 2
        type: OPEN_SIMPLEX_2
        frequency: 0.02
        salt: 2
  
  sampler-2d:
    dimensions: 2
    type: EXPRESSION
    variables: *variables
    expression: (simplex(x/3, z/3)+1)/2*10

tags:
  - LAND_CAVES
  - USE_RIVER

palette:
  - GRASS: $meta.yml:top-y
  - SAND: $meta.yml:ocean-level
  - << meta.yml:palette-bottom

slant:
  - threshold: 0.4
    palette:
      - BLOCK:minecraft:stone: $meta.yml:top-y
      - SAND: ${meta.yml:ocean-level} + 1
      - << meta.yml:palette-bottom

features:
  flora:
    - GRASS