id: SALT_FLATS
type: BIOME
extends:
  - ENVIRONMENT_LAND_DRY_DESERT
  - EQ_CRACKED_FLATS
  - CARVING_OCEAN
  - BASE
color: $biomes/colors.yml:SALT_FLATS

vanilla: minecraft:desert

tags:
  - LAND_CAVES
  - USE_RIVER

palette:
  - SALT: $meta.yml:top-y
  - CALCITE_DIORITE_MIX: ${meta.yml:ocean-level} + 2
  - SAND: $meta.yml:ocean-level
  - << meta.yml:palette-bottom

slant:
  - threshold: 0.4
    palette:
      - BLOCK:minecraft:stone: $meta.yml:top-y
      - << meta.yml:palette-bottom